language: node_js
node_js:
- '7'
- '6'
script:
- npm test
notifications:
  slack:
    secure: GxwabBCcKNNCgwqmF0o+E2oBeecrAFC+ISdUAIqBEw+jv7Xdd721+6mzhA0BTf22b47XxUcfffWgKjr4UmEx2jjcxTT7bIscEaCrJ7yID6ftYg1TLtSJQ8ZFVbWuQA+LQJoYSSKPmBL6cK9w5TjtKmuniQkqNw0J8jIH/7tup5c2/jsX3evAlmDsyy9DlOfbUR1OhLC4cs1qlKAHZoJ6v4tm/wlDPe8GSgdtPtoV/+VccJlIsvfad9CG48vNmy+pL+2BvUJTrFUzCvOeb87v7+LdKHAn0Ch2wfhL1xOQwow3krXY0JBHNTKMlnNYn4wr8rtpmxdTi5o+Hx9Z5SV5vW9GeJe6W+CHfSqBKnvi5hnwTSxalt9l7suIjHLzumoWtOnGqrLEJkgLKhjjNNV54tvK6V7xiY5ujr8rA7DXiFy8N4ZUcnlP7lDTp68MWN4Va40jmZEcoXntgw1vR8C+erIwkD8RcP7jyMy7dl0VmHF3mSFXiIx353uKu9iO3hAOdKPW+diGlwXvQsOx09alGM3F2ZNF9jNxGZtq9SDkW2TOZ0YO5wOmm/tyDCu0cQNilZLbFiEtuvWOdxAoAFcBuY9e1WDnucf/Hkg/Jc4kjWUR5mdP/svd8xsGtJCHSWH+IZxDI0djFrCnA0X5p8iUygUi9VIRn6dEmEs8cOBEAeg=
